apiVersion: v1
kind: Service
metadata:
  name: dpp-monitor-service
spec:
  selector:
    app: dpp-monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer